/// Flutter icons StoreIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StoreIcons
///      fonts:
///       - asset: fonts/StoreIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class StoreIcons {
  StoreIcons._();

  static const _kFontFam = 'StoreIcons';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardpos = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colorfilter = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_arrow_alt_left = IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
